apiVersion: apps/v1
kind: Deployment
metadata: { name: common-media-service }
spec:
  template:
    spec:
      containers:
        - name: common-media-service
          env:
            - { name: MEDIA_ACCESS_KEY, valueFrom: { secretKeyRef: { name: open-im-env, key: MINIO_ROOT_USER } } }
            - { name: MEDIA_SECRET_KEY, valueFrom: { secretKeyRef: { name: open-im-env, key: MINIO_ROOT_PASSWORD } } }
