CREATE TABLE iam_menu (
    id BIGINT NOT NULL,
    parent_id BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    path VARCHAR(255) NULL,
    icon VARCHAR(64) NULL,
    scope_level VARCHAR(32) NOT NULL,
    domain_code VARCHAR(64) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_iam_menu_scope_code (scope_level, code),
    KEY idx_iam_menu_scope_sort (scope_level, sort_no, id)
);

INSERT INTO iam_menu (id, parent_id, code, name, path, icon, scope_level, domain_code, sort_no) VALUES
(1, 0, 'tenant', '租户管理', '/admin/platform/tenants', 'building', 'PLATFORM', 'core', 10),
(2, 0, 'pricing', '计价方案', '/admin/pricing-plans', 'price', 'PLATFORM', 'core', 20),
(3, 0, 'iam', '权限管理', '/admin/iam', 'management', 'PLATFORM', 'core', 30),
(31, 3, 'iam.role', '角色', '/admin/iam/roles', 'avatar', 'PLATFORM', 'core', 31),
(32, 3, 'iam.permission', '权限', '/admin/iam/permissions', 'key', 'PLATFORM', 'core', 32),
(4, 0, 'paymethod', '支付方式', '/admin/platform/payment-methods', 'money', 'PLATFORM', 'core', 40),
(10, 0, 'store', '门店', '/admin/tenant/stores', 'shop', 'TENANT', 'core', 10),
(29, 0, 'tenant.overview', '经营总览', '/admin/tenant/overview', 'dashboard', 'TENANT', 'core', 15),
(27, 0, 'currency', '币种', '/admin/tenant/currency', 'wallet', 'TENANT', 'core', 20),
(11, 0, 'resource', '包厢管理', '/admin/resources', 'grid', 'TENANT', 'core', 30),
(12, 0, 'reservation', '预约管理', '/business/reservations', 'calendar', 'TENANT', 'core', 40),
(13, 0, 'order', '收银台', '/business/orders', 'tickets', 'TENANT', 'core', 50),
(28, 0, 'order-manage', '订单管理', '/admin/orders', 'list', 'TENANT', 'core', 60),
(24, 0, 'inventory', '仓库管理', '/admin/inventory', 'box', 'TENANT', 'core', 70),
(25, 0, 'products', '商品管理', '/admin/products', 'goods', 'TENANT', 'core', 80),
(14, 0, 'payment', '收银/支付', '/business/payments', 'credit-card', 'TENANT', 'core', 90),
(17, 0, 'shift', '交班/日结', '/business/shifts', 'clock', 'TENANT', 'core', 100),
(15, 0, 'report', '报表', '/admin/reports', 'chart', 'TENANT', 'core', 110),
(18, 0, 'member', '客户管理', '/business/members', 'user', 'TENANT', 'core', 120),
(19, 0, 'points', '积分管理', '/business/points', 'star', 'TENANT', 'core', 130),
(20, 0, 'paymethod', '支付方式', '/business/payment-methods', 'collection', 'TENANT', 'core', 140),
(21, 0, 'wallet', '储值管理', '/business/wallet', 'coin', 'TENANT', 'core', 150),
(22, 0, 'security', '脱敏权限', '/admin/security', 'lock', 'TENANT', 'core', 160),
(16, 0, 'ktv', 'KTV 配置', '/admin/ktv/config', 'setting', 'TENANT', 'ktv', 170),
(23, 0, 'staff', '运营人员', '/admin/staff', 'service', 'TENANT', 'core', 180),
(26, 0, 'audit', '审计日志', '/admin/audits', 'document', 'TENANT', 'core', 190);
