-- KTV 异常处理：挂单字段（KTV_BUSINESS_01 §11.1）。
ALTER TABLE ord_order ADD COLUMN hold_reason VARCHAR(255) DEFAULT NULL COMMENT '挂单原因';
ALTER TABLE ord_order ADD COLUMN hold_at DATETIME(3) DEFAULT NULL COMMENT '挂单时间';
