-- 退款审批状态机 PENDING → APPROVED/REJECTED → REFUNDED（KTV_BUSINESS_01 §7.5）。
-- 原脚手架以 REQUESTED 表示申请，归一为 PENDING，历史数据一并迁移。
ALTER TABLE `pay_refund` MODIFY COLUMN `status` varchar(24) NOT NULL DEFAULT 'PENDING'
    COMMENT 'PENDING/APPROVED/REJECTED/REFUNDED';
UPDATE `pay_refund` SET `status` = 'PENDING' WHERE `status` = 'REQUESTED';
