package com.gvchat.im.admin.api.clientrelease;

import com.gvchat.im.admin.api.clientrelease.ClientReleaseDtos.*;
import com.gvchat.im.admin.application.clientrelease.ClientReleaseApplicationService;
import com.gvchat.im.admin.application.clientrelease.ClientReleaseCheckApplicationService;
import com.gvchat.im.admin.domain.clientrelease.model.*;
import com.gvchat.common.dto.PageResult;
import com.gvchat.common.exception.ApiException;
import com.gvchat.common.http.HttpStatusCodes;
import com.gvchat.infrastructure.security.SecurityUser;
import jakarta.validation.Valid;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@RestController
@RequiredArgsConstructor
public class ClientReleaseController {
  private final ClientReleaseApplicationService service;
  private final ClientReleaseCheckApplicationService checkService;
  @PostMapping("/client/release-check") public DataResponse<CheckResponse> check(@Valid @RequestBody CheckRequest request, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { var result = checkService.check(platform(request.platform()), channel(request.channel()), request.buildNumber(), architecture(request.architecture()), request.protocolVersion(), request.installationId()); return data(new CheckResponse(result.decision(), result.blockReason(), result.serverTime(), result.target() == null ? null : response(result.target())), requestId); }
  @GetMapping("/client/releases/latest") public DataResponse<ReleaseResponse> latestRelease(@RequestParam String platform, @RequestParam(defaultValue = "prod") String channel, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return service.latestReleased(platform(platform), channel(channel)).map(this::response).map(release -> data(release, requestId)).orElseGet(() -> data(null, requestId)); }
  @GetMapping("/admin/client-releases") public PageResult<ReleaseResponse> list(@RequestParam(required = false) String platform, @RequestParam(required = false) String channel, @RequestParam(required = false) String status, @RequestParam(required = false) Integer page, @RequestParam(required = false) Integer pageSize) { PageResult<ClientRelease> result = service.list(platform == null ? null : platform(platform), channel == null ? null : channel(channel), status == null ? null : status(status), page, pageSize); return PageResult.<ReleaseResponse>builder().items(result.getItems().stream().map(this::response).toList()).total(result.getTotal()).page(result.getPage()).pageSize(result.getPageSize()).build(); }
  @GetMapping("/admin/client-releases/{id}") public DataResponse<ReleaseResponse> get(@PathVariable long id, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.get(id)), requestId); }
  @PostMapping("/admin/client-releases") @ResponseStatus(HttpStatus.CREATED) public DataResponse<ReleaseResponse> create(@AuthenticationPrincipal SecurityUser user, @Valid @RequestBody CreateRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.create(context(user, requestId, key, request.reason()), release(request))), requestId); }
  @PutMapping("/admin/client-releases/{id}") public DataResponse<ReleaseResponse> update(@AuthenticationPrincipal SecurityUser user, @PathVariable long id, @Valid @RequestBody UpdateRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.updateDraft(context(user, requestId, key, request.reason()), id, request.expectedRowVersion(), release(request))), requestId); }
  @PostMapping("/admin/client-releases/{id}/submit") public DataResponse<ReleaseResponse> submit(@AuthenticationPrincipal SecurityUser user, @PathVariable long id, @Valid @RequestBody SubmitRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.submit(context(user, requestId, key, request.reason()), id, request.expectedRowVersion(), request.initialRolloutPercent(), request.scheduledAt())), requestId); }
  @PostMapping("/admin/client-releases/{id}/rollout") public DataResponse<ReleaseResponse> rollout(@AuthenticationPrincipal SecurityUser user, @PathVariable long id, @Valid @RequestBody RolloutRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.rollout(context(user, requestId, key, request.reason()), id, request.expectedRowVersion(), request.rolloutPercent())), requestId); }
  @PostMapping("/admin/client-releases/{id}/pause") public DataResponse<ReleaseResponse> pause(@AuthenticationPrincipal SecurityUser user, @PathVariable long id, @Valid @RequestBody StateRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.pause(context(user, requestId, key, request.reason()), id, request.expectedRowVersion())), requestId); }
  @PostMapping("/admin/client-releases/{id}/resume") public DataResponse<ReleaseResponse> resume(@AuthenticationPrincipal SecurityUser user, @PathVariable long id, @Valid @RequestBody StateRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.resume(context(user, requestId, key, request.reason()), id, request.expectedRowVersion())), requestId); }
  @PostMapping("/admin/client-releases/{id}/withdraw") public DataResponse<ReleaseResponse> withdraw(@AuthenticationPrincipal SecurityUser user, @PathVariable long id, @Valid @RequestBody StateRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.withdraw(context(user, requestId, key, request.reason()), id, request.expectedRowVersion())), requestId); }
  @PostMapping("/admin/client-releases/{id}/archive") public DataResponse<ReleaseResponse> archive(@AuthenticationPrincipal SecurityUser user, @PathVariable long id, @Valid @RequestBody StateRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(response(service.archive(context(user, requestId, key, request.reason()), id, request.expectedRowVersion())), requestId); }
  @GetMapping("/admin/client-release-policies") public DataResponse<java.util.List<PolicyResponse>> policies(@RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(service.listPolicies().stream().map(this::policyResponse).toList(), requestId); }
  @PutMapping("/admin/client-release-policies/{platform}/{channel}") public DataResponse<PolicyResponse> policy(@AuthenticationPrincipal SecurityUser user, @PathVariable String platform, @PathVariable String channel, @Valid @RequestBody PolicyRequest request, @RequestHeader("Idempotency-Key") UUID key, @RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(policyResponse(service.upsertPolicy(context(user, requestId, key, request.reason()), platform(platform), channel(channel), request.expectedRowVersion(), request.minimumBuildNumber())), requestId); }
  @GetMapping("/admin/client-releases/{id}/audit-logs") public PageResult<AuditResponse> auditLogs(@PathVariable long id, @RequestParam(required = false) Integer page, @RequestParam(required = false) Integer pageSize) { PageResult<ReleaseAuditLog> result = service.listAuditLogs(id, page, pageSize); return PageResult.<AuditResponse>builder().items(result.getItems().stream().map(this::auditResponse).toList()).total(result.getTotal()).page(result.getPage()).pageSize(result.getPageSize()).build(); }
  @GetMapping("/admin/client-release-platforms") public DataResponse<java.util.List<PlatformResponse>> platforms(@RequestHeader(value = "X-Request-Id", required = false) String requestId) { return data(service.platforms().stream().map(item -> new PlatformResponse(item.databaseValue(), service.isEnabled(item))).toList(), requestId); }
  private ClientReleaseApplicationService.WriteContext context(SecurityUser user, String requestId, UUID key, String reason) { return new ClientReleaseApplicationService.WriteContext(user.getId(), requestId(requestId), key.toString(), reason); }
  private ClientRelease release(ReleaseDraftRequest request) { return new ClientRelease(null, platform(request.platform()), channel(request.channel()), request.version(), request.buildNumber(), ReleaseStatus.DRAFT, request.mandatory(), 0, "", null, null, request.releaseNotes(), request.storeUrl(), new CompatibilitySnapshot(request.compatibility().protocolVersion(), request.compatibility().minimumServerCapabilityVersion()), 0L, 0L, null, 0L, null, request.artifacts().stream().map(item -> new ReleaseArtifact(null, null, architecture(item.architecture()), packageType(item.packageType()), item.downloadUrl(), item.sha256(), item.sizeBytes(), item.signingMetadata())).toList()); }
  private ReleaseResponse response(ClientRelease value) { return new ReleaseResponse(value.id(), value.platform().databaseValue(), value.channel().databaseValue(), value.version(), value.buildNumber(), value.status().databaseValue(), value.mandatory(), value.rolloutPercent(), value.scheduledAt(), value.publishedAt(), value.releaseNotes(), value.storeUrl(), value.rowVersion(), new CompatibilityRequest(value.compatibility().protocolVersion(), value.compatibility().minimumServerCapabilityVersion()), value.artifacts().stream().map(item -> new ArtifactResponse(item.architecture().databaseValue(), item.packageType().databaseValue(), item.downloadUrl(), item.sha256(), item.sizeBytes(), item.signingMetadataJson())).toList()); }
  private PolicyResponse policyResponse(ClientReleasePolicy value) { return new PolicyResponse(value.id(), value.platform().databaseValue(), value.channel().databaseValue(), value.minimumBuildNumber(), value.rowVersion(), value.updatedAt()); }
  private AuditResponse auditResponse(ReleaseAuditLog value) { return new AuditResponse(value.id(), value.action().databaseValue(), value.beforeStatus() == null ? null : value.beforeStatus().databaseValue(), value.afterStatus() == null ? null : value.afterStatus().databaseValue(), value.requestId(), value.reason(), value.createdBy(), value.createdAt()); }
  private <T> DataResponse<T> data(T value, String requestId) { return new DataResponse<>(value, requestId(requestId)); }
  private String requestId(String value) { return value == null || value.isBlank() ? UUID.randomUUID().toString() : value; }
  private ReleasePlatform platform(String value) { return parse(() -> ReleasePlatform.fromDatabaseValue(value)); } private ReleaseChannel channel(String value) { return parse(() -> ReleaseChannel.fromDatabaseValue(value)); } private ReleaseStatus status(String value) { return parse(() -> ReleaseStatus.fromDatabaseValue(value)); } private TargetArchitecture architecture(String value) { return parse(() -> TargetArchitecture.fromDatabaseValue(value)); } private PackageType packageType(String value) { return parse(() -> PackageType.fromDatabaseValue(value)); }
  private <T> T parse(java.util.function.Supplier<T> parser) { try { return parser.get(); } catch (IllegalArgumentException exception) { throw new ApiException(HttpStatusCodes.BAD_REQUEST, "CLIENT_RELEASE_INVALID_REQUEST", exception.getMessage()); } }
}
